spring:
  application:
  name: customer
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      database: customer
      password: example
      username: root

server:
  port: 8083
  servlet:
    context-path: /customer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true

monitoring:
  graphite:
    host: grafana-server
    port: 3000
    report-interval: 500
