spring:
  application:
  name: linkconverter
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081
  servlet:
    context-path: /link-converter

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true


monitoring:
  graphite:
    host: localhost
    port: 3000
    report-interval: 500