spring:
  application:
  name: store-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://mysql-server:3306/bootdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa :
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto : update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  persistence:
    upload:
      path: /var/log/java
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081
  servlet:
    context-path: /store-api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true

jwt:
  secret: baseUser
  get:
    token:
      uri: /authenticate

monitoring:
  graphite:
    host: localhost
    port: 3000
    report-interval: 500

FileStorageController:
  saveFile: Authenticates user and returns its JWT token.
